### ISSUE TITLE
Feature Request: bin conversion and cue autocreation

### ISSUE THREAD

**Issue by sahlberg** [ADBeta/psx-comBINe#2]
Don't know if you read psx-place, but I had some ideas of useful extra features you might consider:

Very nice. There is a lack of tools to manage bin and cue files.

Have you thought about adding extra features?
A couple of nice features I think would be :

1, Create a cue from scratch from a single bin/img. Useful if you just have a single bin/img and want to generate a barebones cue for it.
(there are trivial tools and even websites that do this, but it would be nice to have all cue management in one single tool)

2, Create a cue from scratch if you have a bunch of bin files but no cue file.

2 could even be expanded on to detect and convert ISO files into "CD-ROM XA mode 2 form-1" that psx mode2 tracks should be in. (I can give you sources that does this conversion) or even convert "mp3" files into proper CDDA tracks before merging (just call out to ffmpeg?).

Something like:
./psx-comBINe track1.iso track2.mp3 track3.flac -o basename

Then it automatically converts track1 from ISO to XA mode2, and it converts the two audiofiles to the proper format and then merges the three bin files and creates a cue file for them.

That would be really cool and really useful I think.

**Comment by ADBeta** [comment]
Adding these features now.
Thanks for the feedback and apologies for slow response :)

**Comment by ADBeta** [comment]
- Addendum:
Will not be adding CDDA or CD-ROM XA toolset into psx-combine but there is another tool I was working on (psXtract) which will be able to perform some of these actions. I may tie them in together later but for now they are isolated

**Comment by sahlberg** [comment]
Ok. anyway, converting an ISO to XA M2F1 is kinda trivial, steal/get inspired by this code :   https://github.com/sahlberg/pop-fe/blob/master/iso2xa.py
Conversion of audio files/tracks should be easy to do too by just forking out a child process to call ffmpeg.

Looking forward to see the results.   This king of tooling would be very useful to have.

**Comment by sahlberg** [comment]
Just an FYI about the name psXtract.
There is already a tool called psxtract (https://github.com/AKuHAK/psxtract.git)
which is used to decrypt and extract game data from encrypted EBOOT.PBP for PS-Classic games on PSP/PS3.

**Comment by ADBeta** [comment]
thanks for the info! 
I don't have much time these days so it might be slow progress.

**Comment by ADBeta** [comment]
Version 3.6 now supports this! Thanks for the suggestion :)
