### ISSUE TITLE
Linking Problem with Boost::Filesystem + Solution

### ISSUE THREAD

**Issue by SneakyyPeakyy** [ADBeta/psx-comBINe#4]
When every i compiled the app i got the following error:
``undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'``

After some try and error i switched from the `g++` to `clang++`. With this change i was able to compile without any problems. So if anybody has the same problem maybe this works for you as well. The root of the Problem seems to be in Boost itself, at least that's what i found in my research. Source: https://stackoverflow.com/questions/15634114/cant-link-program-using-boost-filesystem/17988317#17988317

**Comment by ADBeta** [comment]
I have been really busy recently, but I am slowly working on a new version that doesn't use boost, but uses C++17 so it is no longer needed. 

If you want to close this issue due to that, or wait until it's released is up to you
